version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus-app
    container_name: perpus-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage/app/public:/var/www/public/storage
    networks:
      - perpus-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: perpus-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - perpus-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: perpus-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: perpus
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: perpus
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perpus-network

  redis:
    image: redis:7-alpine
    container_name: perpus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - perpus-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: perpus-queue
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - perpus-network
    depends_on:
      - app
      - db
      - redis

networks:
  perpus-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
